### ISSUE TITLE
FileNotFoundError: could not find topas binary at ... during execution of RunOptimisation_main.py

### ISSUE THREAD

**Issue by joker-li717** [Image-X-Institute/TopasOpt#135]
Hello,
I encountered an issue while running the RunOptimisation_main.py script in the ApertureOptimisation example. Here are the details:

**Error message**
Traceback (most recent call last):
  File "RunOptimisation_main.py", line 33, in <module>
    Optimiser = to.BayesianOptimiser(optimisation_params=optimisation_params, BaseDirectory=BaseDirectory,
  File "/home/mywsl/topasopt/TopasOptVenv/lib/python3.8/site-packages/TopasOpt/Optimisers.py", line 703, in __init__
    super().__init__(**kwds)
  File "/home/mywsl/topasopt/TopasOptVenv/lib/python3.8/site-packages/TopasOpt/Optimisers.py", line 164, in __init__
    self._CheckInputData()
  File "/home/mywsl/topasopt/TopasOptVenv/lib/python3.8/site-packages/TopasOpt/Optimisers.py", line 281, in _CheckInputData
    raise FileNotFoundError(error)
FileNotFoundError: could not find topas binary at
/home/mywsl/Applications/TOPAS/OpenTOPAS-install/bin/topas
Please initialise with TopasLocation pointing to the topas installation location.
Quitting

**What I have done**

1. Installed TOPAS
I installed topas and confirmed that the binary is located at
 /home/mywsl/Applications/TOPAS/OpenTOPAS-install/bin/topas.

2. Verified the binary is executable
chmod +x /home/mywsl/Applications/TOPAS/OpenTOPAS-install/bin/topas

3. Set the environment variable
export TOPAS_LOCATION=/home/mywsl/Applications/TOPAS/OpenTOPAS-install/bin/topas

4. Modified the script
Updated the RunOptimisation_main.py script to include the correct TopasLocation:
Optimiser = to.BayesianOptimiser(
    optimisation_params=optimisation_params,
    BaseDirectory=BaseDirectory,
    TopasLocation="/home/mywsl/Applications/TOPAS/OpenTOPAS-install/bin/topas",
    ...
)

**Environment**
- OS: Windows Subsystem for Linux (Ubuntu 24.04)
- Python version: 3.8
- Virtual environment: Yes
- Topas version: 4.0

**Additional information**
I suspect the issue might be related to:
- A missing shared library (libQt5Widgets.so.5 was an issue earlier but resolved by installing libqt5widgets5).
- A misconfiguration in _CheckInputData.

Could you please confirm whether this is an issue with the script or my configuration?
Thank you for your assistance!

![Snipaste_2024-12-11_10-47-06](https://github.com/user-attachments/assets/7d1461d9-924c-41ac-ac52-b26854e28867)

**Comment by bwheelz36** [comment]
Hi, sorry for the slow reply. 
here's where this error comes from:
```python
if not os.path.isfile(self.TopasLocation / 'bin' / 'topas'):
    error = f'{bcolors.FAIL}could not find topas binary at \n{self.TopasLocation} ' \
            f'\nPlease initialise with TopasLocation pointing to the topas installation location.' \
            f'\nQuitting{bcolors.ENDC}'
    raise FileNotFoundError(error)
```

rather than  `=/home/mywsl/Applications/TOPAS/OpenTOPAS-install/bin/topas`
you need to point to `=/home/mywsl/Applications/TOPAS/OpenTOPAS-install`

**Comment by joker-li717** [comment]
Hi! No worries at all. Your help was incredibly valuable, and I truly appreciate it. I was able to resolve the issue smoothly thanks to your guidance. Have a great day!
